
BLENDER="C:\Program Files\Blender Foundation\Blender 2.90\blender.exe"
DIST=../dist

all : \
    $(DIST)/hexapod.pnct \
    $(DIST)/hexapod.scene \

$(DIST)/hexapod.scene : hexapod.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "hexapod.blend:Main" "$(DIST)/hexapod.scene"

$(DIST)/hexapod.pnct : hexapod.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "hexapod.blend:Main" "$(DIST)/hexapod.pnct" 
